2024-06-05 19:33:28 - root - INFO - Server listening on localhost:12345
2024-06-05 19:33:38 - root - INFO - Connection from ('127.0.0.1', 57900)
2024-06-05 19:33:40 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B8995DE690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:33:40 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:33:40 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 19:33:50 - root - ERROR - Timeout occurred while trying to connect to the Flask server. Shutting down the socket server.
2024-06-05 19:34:32 - root - INFO - Server listening on localhost:12345
2024-06-05 19:34:42 - root - ERROR - Timeout occurred while trying to connect to the Flask server. Shutting down the socket server.
2024-06-05 19:36:43 - root - INFO - Server listening on localhost:12345
2024-06-05 19:36:47 - root - INFO - Connection from ('127.0.0.1', 57919)
2024-06-05 19:36:47 - root - ERROR - Failed to connect to the Flask server for shutdown
2024-06-05 19:36:53 - root - INFO - Server listening on localhost:12345
2024-06-05 19:36:56 - root - INFO - Connection from ('127.0.0.1', 57925)
2024-06-05 19:36:58 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CB4F5AE5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:36:58 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:36:58 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 19:37:08 - root - ERROR - Timeout occurred while trying to connect to the Flask server. Shutting down the socket server.
2024-06-05 19:37:53 - root - INFO - Server listening on localhost:12345
2024-06-05 19:37:57 - root - INFO - Connection from ('127.0.0.1', 57934)
2024-06-05 19:37:58 - root - ERROR - Failed to connect to the Flask server for shutdown
2024-06-05 19:38:03 - root - INFO - Server listening on localhost:12345
2024-06-05 19:38:05 - root - INFO - Connection from ('127.0.0.1', 57940)
2024-06-05 19:38:07 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002350751E690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:38:07 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:38:07 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 19:38:17 - root - ERROR - Timeout occurred while trying to connect to the Flask server. Shutting down the socket server.
2024-06-05 19:40:20 - root - INFO - Server listening on localhost:12345
2024-06-05 19:40:24 - root - INFO - Connection from ('127.0.0.1', 57963)
2024-06-05 19:40:24 - root - ERROR - Failed to connect to the Flask server for shutdown
2024-06-05 19:40:31 - root - INFO - Server listening on localhost:12345
2024-06-05 19:40:34 - root - INFO - Connection from ('127.0.0.1', 57969)
2024-06-05 19:40:36 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E617DE5D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:40:36 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:40:36 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 19:40:46 - root - ERROR - Timeout occurred while trying to connect to the Flask server. Shutting down the socket server.
2024-06-05 19:44:04 - root - INFO - Server listening on localhost:12345
2024-06-05 19:44:10 - root - INFO - Connection from ('127.0.0.1', 57996)
2024-06-05 19:44:12 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000281993404D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:44:12 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:44:12 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 19:45:18 - root - INFO - Server listening on localhost:12345
2024-06-05 19:45:25 - root - INFO - Connection from ('127.0.0.1', 58008)
2024-06-05 19:45:27 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000014FB01A04D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 19:45:27 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 19:45:27 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:30:49 - root - INFO - Server listening on localhost:12345
2024-06-05 20:31:03 - root - INFO - Connection from ('127.0.0.1', 58174)
2024-06-05 20:31:05 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002068B92E010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 20:31:05 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 20:31:05 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:31:35 - root - INFO - Connection from ('127.0.0.1', 58179)
2024-06-05 20:31:37 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002068ADD54D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 20:31:37 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 20:31:37 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:32:41 - root - INFO - Server listening on localhost:12345
2024-06-05 20:32:46 - root - INFO - Connection from ('127.0.0.1', 58195)
2024-06-05 20:32:48 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001877D0FE610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 20:32:48 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 20:32:48 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:34:19 - root - INFO - Server listening on localhost:12345
2024-06-05 20:34:43 - root - INFO - Connection from ('127.0.0.1', 58214)
2024-06-05 20:34:45 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247AFEEAF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 20:34:45 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 20:34:45 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:35:46 - root - INFO - Server listening on localhost:12345
2024-06-05 20:35:55 - root - INFO - Connection from ('127.0.0.1', 58228)
2024-06-05 20:35:57 - root - ERROR - Failed to connect to the Flask server for public key: HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /publickey (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000229DB43E010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-06-05 20:35:57 - root - ERROR - Error handling data: Flask server is inactive or unreachable
2024-06-05 20:35:57 - root - ERROR - Failed to handle data: Flask server is inactive or unreachable
2024-06-05 20:36:05 - root - INFO - Server listening on localhost:12345
2024-06-05 20:36:15 - root - INFO - Connection from ('127.0.0.1', 58235)
2024-06-05 20:36:15 - root - ERROR - Failed to connect to the Flask server for shutdown
